use_frameworks!

platform :ios, '12.0'

target 'BlueSTSDK_Gui_Example' do
  pod 'BlueSTSDK_Gui', :path => '../'
  pod 'STTheme', :path => '../../STTheme'
  pod 'BlueSTSDK', :path => '../../BlueSTSDK'
  
  target 'BlueSTSDK_Gui_Tests' do
    inherit! :search_paths

    
  end
end
