platform :ios, '11.0'

inhibit_all_warnings!

use_frameworks!

abstract_target 'defaults' do

  pod 'TrackerThresholdUtil', :path => '../'
  pod 'BlueSTSDK', :path => '../../BlueSTSDK'
  pod 'AssetTrackingDataModel', :path => '../../AssetTrackingDataModel'
  
  target 'TrackerThresholdUtil_Example'
  target 'TrackerThresholdUtil_Tests'
end
