use_frameworks!

platform :ios, '12.0'

target 'BlueSTSDK_Analytics_Example' do
  pod 'BlueSTSDK_Analytics', :path => '../'
  pod 'BlueSTSDK', :path => '../../BlueSTSDK'
  pod 'BlueSTSDK_Gui', :path => '../../BlueSTSDK_Gui'
  pod 'STTheme', :path => '../../STTheme'

  target 'BlueSTSDK_Analytics_Tests' do
    inherit! :search_paths

    
  end
end
