platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

target 'STTrilobyte_Example' do
  pod 'STTrilobyte', :path => '../'
  
  pod 'BlueSTSDK_Gui', :path => '../../BlueSTSDK_Gui'
  pod 'BlueSTSDK', :path => '../../BlueSTSDK'
  pod 'STTheme', :path => '../../STTheme'

  target 'STTrilobyte_Tests' do
    inherit! :search_paths

    
  end
end
