platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

target 'AssetTrackingDataModel_Example' do
  pod 'AssetTrackingDataModel', :path => '../'

  target 'AssetTrackingDataModel_Tests' do
    inherit! :search_paths

    
  end
end
