platform :ios, '11.0'

inhibit_all_warnings!

use_frameworks!

abstract_target 'defaults' do

  pod 'AssetTrackingCloudDashboard', :path => '../'
  pod 'AssetTrackingDataModel', :path => '../../AssetTrackingDataModel'
  pod 'SmarTagLib', :path => '../../SmarTagLib'
  
  target 'AssetTrackingCloudDashboard_Example'
  target 'AssetTrackingCloudDashboard_Tests'
end
