use_frameworks!

platform :ios, '12.0'

target 'BlueMSFwUpgradeChecker_Example' do
  pod 'BlueMSFwUpgradeChecker', :path => '../'

  target 'BlueMSFwUpgradeChecker_Tests' do
    inherit! :search_paths

    
  end
end
